import './globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'HeBraTech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode}) {
  return (
    <html lang="en">
        <body className='overflow-x-hidden bg-main-black'>
          {children}
        </body>
    </html>
  )
}
